services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kfc
      POSTGRES_PASSWORD: kfc
      POSTGRES_DB: kfc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kfc@kfc.com
      PGADMIN_DEFAULT_PASSWORD: kfc
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
